version: '3.9'

services:
  db:
    image: postgres:latest  
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
    ports:
      - 5432:5432

  redis:
    image: redis:latest  
    container_name: redis_cache
    ports:
      - 6379:6379

volumes:
  postgres_data: